// <auto-generated />
namespace TextUml.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSharedWithEmailsToDocument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSharedWithEmailsToDocument));
        
        string IMigrationMetadata.Id
        {
            get { return "201305221215446_AddSharedWithEmailsToDocument"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
